sudo:required
services:
  - docker
before_install:
  - docker build -t 4990814/client -f ./testdocker/Dockerfile.dev ./testdocker


script:
  - docker run 4990814/client-prod npm run test -- --coverage

after_success:
  - docker build -t 4990814/nginx-prod ./nginx
  - docker build -t 4990814/server-prod ./server
  - docker build -t 4990814/client-prod ./testdocker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 4990814/nginx-prod
  - docker push 4990814/server-prod
  - docker push 4990814/client-prod